# Generated by Django 2.1.7 on 2019-04-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
