# Generated by Django 2.1.5 on 2019-03-20 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLuas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('TrainCode', models.CharField(max_length=10, null=True)),
                ('StationFullName', models.CharField(max_length=100, null=True)),
                ('StationCode', models.CharField(max_length=6, null=True)),
                ('QueryTime', models.TimeField(null=True)),
                ('TrainDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Origin', models.CharField(max_length=100, null=True)),
                ('Destination', models.CharField(max_length=100, null=True)),
                ('OriginTime', models.TimeField(null=True)),
                ('DestinationTime', models.TimeField(null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('LastLocation', models.CharField(max_length=100, null=True)),
                ('DueIn', models.IntegerField(null=True)),
                ('Late', models.IntegerField(null=True)),
                ('ExpArrival', models.TimeField(null=True)),
                ('ExpDepart', models.TimeField(null=True)),
                ('SchArrival', models.TimeField(null=True)),
                ('SchDepart', models.TimeField(null=True)),
                ('Direction', models.CharField(max_length=20, null=True)),
                ('TrainType', models.CharField(max_length=20, null=True)),
                ('LocationType', models.CharField(max_length=1, null=True)),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IrishRailStationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationDesc', models.CharField(max_length=100, null=True)),
                ('StationAlias', models.CharField(max_length=100, null=True)),
                ('StationLatitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('StationLongitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('StationCode', models.CharField(max_length=6, null=True)),
                ('StationId', models.IntegerField()),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
