# Generated by Django 2.1.5 on 2019-03-23 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBusStopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusStopNumber', models.CharField(max_length=100, null=True)),
                ('BusStopStationName', models.CharField(max_length=100, null=True)),
                ('BusStopLatitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('BusStopLongitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
