# Generated by Django 2.1.7 on 2019-04-06 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0002_dublinbusstopdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBusRealTimeStopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusStopNumber', models.CharField(max_length=100, null=True)),
                ('BusStopRouteNumber', models.CharField(max_length=100, null=True)),
                ('BusStopIncomingTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('BusStopZone', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DublinBusStopZoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusStopNumber', models.CharField(max_length=100, null=True)),
                ('BusStopZone', models.CharField(max_length=100, null=True)),
                ('BusStopRoute', models.CharField(max_length=100, null=True)),
                ('BusStopIncomingTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='dublinbusstopdata',
            name='BusStopZone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
