# Generated by Django 2.2 on 2019-04-03 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0004_dublinbusstopdata_busstopzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBusStopZoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusStopNumber', models.CharField(max_length=100, null=True)),
                ('BusStopZone', models.CharField(max_length=100, null=True)),
                ('BusStopRoute', models.CharField(max_length=100, null=True)),
                ('BusStopIncomingTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
