# Generated by Django 2.1.5 on 2019-03-20 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('contract_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('position_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('position_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('banking', models.BooleanField(max_length=5)),
                ('bonus', models.BooleanField(max_length=5)),
                ('bike_stands', models.IntegerField()),
                ('available_bike_stands', models.IntegerField()),
                ('available_bikes', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField(verbose_name='date published')),
                ('cm_last_insert_dttm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
